### ISSUE TITLE
hardcoded key ?

### ISSUE THREAD

**Issue by GhostRock37** [HiS3/Ivanti-ICT-Snapshot-decryption#1]
hello,

thanks for your work ! i want to test your job but i don't find were is my hardcoded key for decrypt the snapshot ?
can you tell me how to recover this key? and I suppose I have to enter it in your script?

:)

**Comment by HiS3** [comment]
Hey , the key is always the same for the ICT snapshot. So it should work with the key in the python script.

**Comment by GhostRock37** [comment]
Yes it's the same key.... Work well. Thank you!!!

**Comment by HiS3** [comment]
Very good 👍, so I'll close the issues.
